defmodule LagoClient.FeeObject do
  @moduledoc """
  Provides struct and type for a FeeObject
  """
  use LagoClient.Encoder

  @type t :: %__MODULE__{
          __info__: map,
          amount_cents: integer,
          amount_currency: String.t(),
          amount_details: LagoClient.FeeAmountDetails.t() | nil,
          applied_taxes: [LagoClient.FeeAppliedTaxObject.t()] | nil,
          created_at: DateTime.t() | nil,
          event_transaction_id: String.t() | nil,
          events_count: integer | nil,
          external_customer_id: String.t() | nil,
          external_subscription_id: String.t() | nil,
          failed_at: DateTime.t() | nil,
          from_date: DateTime.t() | nil,
          invoice_display_name: String.t() | nil,
          invoiceable: boolean,
          item: LagoClient.FeeObjectItem.t(),
          lago_charge_filter_id: String.t() | nil,
          lago_charge_id: String.t() | nil,
          lago_customer_id: String.t() | nil,
          lago_id: String.t() | nil,
          lago_invoice_id: String.t() | nil,
          lago_subscription_id: String.t() | nil,
          lago_true_up_fee_id: String.t() | nil,
          lago_true_up_parent_fee_id: String.t() | nil,
          pay_in_advance: boolean,
          payment_status: String.t(),
          precise_amount: String.t() | nil,
          precise_total_amount: String.t() | nil,
          precise_unit_amount: String.t(),
          refunded_at: DateTime.t() | nil,
          self_billed: boolean | nil,
          succeeded_at: DateTime.t() | nil,
          taxes_amount_cents: integer,
          taxes_precise_amount: String.t() | nil,
          taxes_rate: number,
          to_date: DateTime.t() | nil,
          total_amount_cents: integer,
          total_amount_currency: String.t(),
          units: String.t()
        }

  defstruct [
    :__info__,
    :amount_cents,
    :amount_currency,
    :amount_details,
    :applied_taxes,
    :created_at,
    :event_transaction_id,
    :events_count,
    :external_customer_id,
    :external_subscription_id,
    :failed_at,
    :from_date,
    :invoice_display_name,
    :invoiceable,
    :item,
    :lago_charge_filter_id,
    :lago_charge_id,
    :lago_customer_id,
    :lago_id,
    :lago_invoice_id,
    :lago_subscription_id,
    :lago_true_up_fee_id,
    :lago_true_up_parent_fee_id,
    :pay_in_advance,
    :payment_status,
    :precise_amount,
    :precise_total_amount,
    :precise_unit_amount,
    :refunded_at,
    :self_billed,
    :succeeded_at,
    :taxes_amount_cents,
    :taxes_precise_amount,
    :taxes_rate,
    :to_date,
    :total_amount_cents,
    :total_amount_currency,
    :units
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amount_cents: :integer,
      amount_currency:
        {:enum,
         [
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      amount_details: {LagoClient.FeeAmountDetails, :t},
      applied_taxes: [{LagoClient.FeeAppliedTaxObject, :t}],
      created_at: {:union, [{:string, :date_time}, :null]},
      event_transaction_id: {:union, [{:string, :generic}, :null]},
      events_count: :integer,
      external_customer_id: {:union, [{:string, :generic}, :null]},
      external_subscription_id: {:union, [{:string, :generic}, :null]},
      failed_at: {:union, [{:string, :date_time}, :null]},
      from_date: {:union, [{:string, :date_time}, :null]},
      invoice_display_name: {:string, :generic},
      invoiceable: :boolean,
      item: {LagoClient.FeeObjectItem, :t},
      lago_charge_filter_id: {:union, [{:string, :uuid}, :null]},
      lago_charge_id: {:union, [{:string, :uuid}, :null]},
      lago_customer_id: {:union, [{:string, :uuid}, :null]},
      lago_id: {:union, [{:string, :uuid}, :null]},
      lago_invoice_id: {:union, [{:string, :uuid}, :null]},
      lago_subscription_id: {:union, [{:string, :uuid}, :null]},
      lago_true_up_fee_id: {:union, [{:string, :uuid}, :null]},
      lago_true_up_parent_fee_id: {:union, [{:string, :uuid}, :null]},
      pay_in_advance: :boolean,
      payment_status: {:enum, ["pending", "succeeded", "failed", "refunded"]},
      precise_amount: {:string, :generic},
      precise_total_amount: {:string, :generic},
      precise_unit_amount: {:string, :generic},
      refunded_at: {:union, [{:string, :date_time}, :null]},
      self_billed: :boolean,
      succeeded_at: {:union, [{:string, :date_time}, :null]},
      taxes_amount_cents: :integer,
      taxes_precise_amount: {:string, :generic},
      taxes_rate: :number,
      to_date: {:union, [{:string, :date_time}, :null]},
      total_amount_cents: :integer,
      total_amount_currency:
        {:enum,
         [
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      units: {:string, :generic}
    ]
  end
end
