defmodule LagoClient.WalletObject do
  @moduledoc """
  Provides struct and type for a WalletObject
  """
  use LagoClient.Encoder

  @type t :: %__MODULE__{
          __info__: map,
          balance_cents: integer,
          consumed_credits: String.t(),
          created_at: DateTime.t(),
          credits_balance: String.t(),
          credits_ongoing_balance: String.t(),
          credits_ongoing_usage_balance: String.t(),
          currency: String.t(),
          expiration_at: DateTime.t() | nil,
          external_customer_id: String.t(),
          invoice_requires_successful_payment: boolean | nil,
          lago_customer_id: String.t(),
          lago_id: String.t(),
          last_balance_sync_at: DateTime.t() | nil,
          last_consumed_credit_at: DateTime.t() | nil,
          name: String.t() | nil,
          ongoing_balance_cents: integer,
          ongoing_usage_balance_cents: integer,
          rate_amount: String.t(),
          recurring_transaction_rules: [LagoClient.WalletRecurringTransactionRule.t()] | nil,
          status: String.t(),
          terminated_at: DateTime.t() | nil
        }

  defstruct [
    :__info__,
    :balance_cents,
    :consumed_credits,
    :created_at,
    :credits_balance,
    :credits_ongoing_balance,
    :credits_ongoing_usage_balance,
    :currency,
    :expiration_at,
    :external_customer_id,
    :invoice_requires_successful_payment,
    :lago_customer_id,
    :lago_id,
    :last_balance_sync_at,
    :last_consumed_credit_at,
    :name,
    :ongoing_balance_cents,
    :ongoing_usage_balance_cents,
    :rate_amount,
    :recurring_transaction_rules,
    :status,
    :terminated_at
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      balance_cents: :integer,
      consumed_credits: {:string, :generic},
      created_at: {:string, :date_time},
      credits_balance: {:string, :generic},
      credits_ongoing_balance: {:string, :generic},
      credits_ongoing_usage_balance: {:string, :generic},
      currency:
        {:enum,
         [
           "AED",
           "AFN",
           "ALL",
           "AMD",
           "ANG",
           "AOA",
           "ARS",
           "AUD",
           "AWG",
           "AZN",
           "BAM",
           "BBD",
           "BDT",
           "BGN",
           "BIF",
           "BMD",
           "BND",
           "BOB",
           "BRL",
           "BSD",
           "BWP",
           "BYN",
           "BZD",
           "CAD",
           "CDF",
           "CHF",
           "CLF",
           "CLP",
           "CNY",
           "COP",
           "CRC",
           "CVE",
           "CZK",
           "DJF",
           "DKK",
           "DOP",
           "DZD",
           "EGP",
           "ETB",
           "EUR",
           "FJD",
           "FKP",
           "GBP",
           "GEL",
           "GIP",
           "GMD",
           "GNF",
           "GTQ",
           "GYD",
           "HKD",
           "HNL",
           "HRK",
           "HTG",
           "HUF",
           "IDR",
           "ILS",
           "INR",
           "ISK",
           "JMD",
           "JPY",
           "KES",
           "KGS",
           "KHR",
           "KMF",
           "KRW",
           "KYD",
           "KZT",
           "LAK",
           "LBP",
           "LKR",
           "LRD",
           "LSL",
           "MAD",
           "MDL",
           "MGA",
           "MKD",
           "MMK",
           "MNT",
           "MOP",
           "MRO",
           "MUR",
           "MVR",
           "MWK",
           "MXN",
           "MYR",
           "MZN",
           "NAD",
           "NGN",
           "NIO",
           "NOK",
           "NPR",
           "NZD",
           "PAB",
           "PEN",
           "PGK",
           "PHP",
           "PKR",
           "PLN",
           "PYG",
           "QAR",
           "RON",
           "RSD",
           "RUB",
           "RWF",
           "SAR",
           "SBD",
           "SCR",
           "SEK",
           "SGD",
           "SHP",
           "SLL",
           "SOS",
           "SRD",
           "STD",
           "SZL",
           "THB",
           "TJS",
           "TOP",
           "TRY",
           "TTD",
           "TWD",
           "TZS",
           "UAH",
           "UGX",
           "USD",
           "UYU",
           "UZS",
           "VND",
           "VUV",
           "WST",
           "XAF",
           "XCD",
           "XOF",
           "XPF",
           "YER",
           "ZAR",
           "ZMW"
         ]},
      expiration_at: {:union, [{:string, :date_time}, :null]},
      external_customer_id: {:string, :generic},
      invoice_requires_successful_payment: :boolean,
      lago_customer_id: {:string, :uuid},
      lago_id: {:string, :uuid},
      last_balance_sync_at: {:union, [{:string, :date_time}, :null]},
      last_consumed_credit_at: {:union, [{:string, :date_time}, :null]},
      name: {:string, :generic},
      ongoing_balance_cents: :integer,
      ongoing_usage_balance_cents: :integer,
      rate_amount: {:string, :generic},
      recurring_transaction_rules: [{LagoClient.WalletRecurringTransactionRule, :t}],
      status: {:enum, ["active", "terminated"]},
      terminated_at: {:union, [{:string, :date_time}, :null]}
    ]
  end
end
